version: "3.8"

services:
  teamhub:
    image: teamhub
    container_name: teamhub_nodejs
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    tty: true
  database:
    image: mongo
    container_name: teamhub_mongodb
    hostname: teamhub_mongodb
    restart: on-failure 
    volumes:
      - ./docker/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    command: mongod --replSet rs0
  mongoinit:
    image: mongo
    restart: "no"
    depends_on:
      - database
    command: >
      mongo --host teamhub_mongodb:27017 --eval
      '
      rs.initiate();
      '